/**
 * Mã lỗi chuẩn hóa — dùng trong Exception Filter (RFC 7807)
 * Format: MODULE_ERROR_DESCRIPTION
 * Phân nhóm theo module nghiệp vụ
 */

// === AUTH ===
export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS';
export const AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND';
export const AUTH_USER_INACTIVE = 'AUTH_USER_INACTIVE';
export const AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED';
export const AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN';
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID';
export const AUTH_INVALID_OTP = 'AUTH_INVALID_OTP';
export const AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED';
export const AUTH_OTP_LOCKED = 'AUTH_OTP_LOCKED';
export const AUTH_GOOGLE_FAILED = 'AUTH_GOOGLE_FAILED';
export const AUTH_FORBIDDEN = 'AUTH_FORBIDDEN';
export const AUTH_RATE_LIMITED = 'AUTH_RATE_LIMITED';

// === USER ===
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_ADDRESS_LIMIT = 'USER_ADDRESS_LIMIT';
export const USER_ADDRESS_NOT_FOUND = 'USER_ADDRESS_NOT_FOUND';

// === PRODUCT ===
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
export const PRODUCT_SLUG_EXISTS = 'PRODUCT_SLUG_EXISTS';
export const PRODUCT_VARIANT_NOT_FOUND = 'PRODUCT_VARIANT_NOT_FOUND';
export const PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK';
export const PRODUCT_IMAGE_UPLOAD_FAILED = 'PRODUCT_IMAGE_UPLOAD_FAILED';
export const PRODUCT_IMAGE_LIMIT = 'PRODUCT_IMAGE_LIMIT';

// === CATEGORY ===
export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
export const CATEGORY_HAS_PRODUCTS = 'CATEGORY_HAS_PRODUCTS';
export const CATEGORY_SLUG_EXISTS = 'CATEGORY_SLUG_EXISTS';

// === CART ===
export const CART_NOT_FOUND = 'CART_NOT_FOUND';
export const CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND';
export const CART_ITEM_LIMIT = 'CART_ITEM_LIMIT';
export const CART_EMPTY = 'CART_EMPTY';

// === CHECKOUT ===
export const CHECKOUT_SESSION_NOT_FOUND = 'CHECKOUT_SESSION_NOT_FOUND';
export const CHECKOUT_SESSION_EXPIRED = 'CHECKOUT_SESSION_EXPIRED';
export const CHECKOUT_STOCK_INSUFFICIENT = 'CHECKOUT_STOCK_INSUFFICIENT';

// === ORDER ===
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
export const ORDER_CANNOT_CANCEL = 'ORDER_CANNOT_CANCEL';
export const ORDER_INVALID_STATUS_TRANSITION = 'ORDER_INVALID_STATUS_TRANSITION';
export const ORDER_ALREADY_REVIEWED = 'ORDER_ALREADY_REVIEWED';

// === PAYMENT ===
export const PAYMENT_BANK_TRANSFER_FAILED = 'PAYMENT_BANK_TRANSFER_FAILED';
export const PAYMENT_INVALID_SIGNATURE = 'PAYMENT_INVALID_SIGNATURE';
export const PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED';

// === VOUCHER ===
export const VOUCHER_NOT_FOUND = 'VOUCHER_NOT_FOUND';
export const VOUCHER_EXPIRED = 'VOUCHER_EXPIRED';
export const VOUCHER_USAGE_LIMIT = 'VOUCHER_USAGE_LIMIT';
export const VOUCHER_MIN_ORDER = 'VOUCHER_MIN_ORDER';
export const VOUCHER_VIP_REQUIRED = 'VOUCHER_VIP_REQUIRED';
export const VOUCHER_ALREADY_USED = 'VOUCHER_ALREADY_USED';
export const VOUCHER_CODE_EXISTS = 'VOUCHER_CODE_EXISTS';

// === REVIEW ===
export const REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND';
export const REVIEW_NOT_PURCHASED = 'REVIEW_NOT_PURCHASED';
export const REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS';

// === BLOG ===
export const BLOG_NOT_FOUND = 'BLOG_NOT_FOUND';
export const BLOG_SLUG_EXISTS = 'BLOG_SLUG_EXISTS';

// === NOTIFICATION ===
export const NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND';

// === GENERAL ===
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
export const NOT_FOUND = 'NOT_FOUND';
